version: '2'
services:
    nginx:
      image: nginx
      container_name: nginx
      ports:
         - "80:80"
         - "443:443"
      network_mode: "host"
      volumes:
         - ./certs:/etc/nginx/certs
         - ./conf.d:/etc/nginx/conf.d
         - ./include-static:/etc/nginx/include-static
         - ./logs:/var/log/nginx
