version: '2'
services:
    nginx:
      image: nginx
      container_name: nginx
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./certs:/etc/nginx/certs
         - ./sites-enabled:/etc/nginx/sites-enabled
         - ./include-static:/etc/nginx/include-static
         - ./logs:/var/log/nginx
